export const ADD_MEMO = "ADD_MEMO";
export const ADD_MEMO_SUCCESS = 'ADD_MEMO_SUCCESS';
export const ADD_MEMO_FAILURE = 'ADD_MEMO_FAILURE';

export const LOAD_MEMO = "LOAD_MEMO";
export const LOAD_MEMO_SUCCESS = 'LOAD_MEMO_SUCCESS';
export const LOAD_MEMO_FAILURE = 'LOAD_MEMO_FAILURE';

export const DELETE_MEMO = "DELETE_MEMO";
export const DELETE_MEMO_SUCCESS = "DELETE_MEMO_SUCCESS"
export const DELETE_MEMO_FAILURE = "DELETE_MEMO_FAILURE"

export const UPDATE_MEMO = "UPDATE_MEMO";
export const UPDATE_MEMO_SUCCESS = "UPDATE_MEMO_SUCCESS"
export const UPDATE_MEMO_FAILURE = "UPDATE_MEMO_FAILURE"

export const SELECT_CURRENT_MEMO = "SELECT_CURRENT_MEMO"
export const DESELECT_CURRENT_MEMO = "DESELECT_CURRENT_MEMO"

export const CHANGE_MEMO_TITLE = "CHANGE_MEMO_TITLE"
export const CHANGE_MEMO_CONTENT = "CHANGE_MEMO_CONTENT"